import React,{useEffect,useState} from 'react';
import { Download,Plus,RefreshCw,Search,WalletCards } from 'lucide-react';
import { DBUser,VAdherentComplet } from '../types';
import { adherentService } from '../services/adherentService';
import { Rachat,RachatStatut,rachatService } from '../services/rachatService';
import { formatFCFA,formatDateFr } from '../utils/formatters';
import { ScrollableTableWrapper } from '../components/common/ScrollableTableWrapper';

export default function Rachats({currentUser}:{currentUser:DBUser}){
 const [rows,setRows]=useState<Rachat[]>([]),[ads,setAds]=useState<VAdherentComplet[]>([]),[busy,setBusy]=useState(false),[show,setShow]=useState(false),[search,setSearch]=useState(''),[statut,setStatut]=useState('TOUS'),[message,setMessage]=useState('');
 const [form,setForm]=useState({adherentId:'',dateDemande:new Date().toISOString().slice(0,10),motif:''});
 const load=async()=>{setBusy(true);const [r,a]=await Promise.all([rachatService.list({search,statut}),adherentService.getAdherents({statut:'ACTIF'})]);setRows(r.data);setAds(a.data);setMessage(r.error?.message??a.error?.message??'');setBusy(false)};
 useEffect(()=>{void load()},[statut]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);const r=await rachatService.create(form);setMessage(r.error?.message??'Dossier de rachat calculé et ouvert.');if(!r.error){setShow(false);await load()}setBusy(false)};
 const advance=async(r:Rachat)=>{let next:Exclude<RachatStatut,'DOSSIER_OUVERT'|'PAYE'>|null=r.statut==='DOSSIER_OUVERT'?'EN_CONTROLE':r.statut==='EN_CONTROLE'?'VALIDE':null;if(!next)return;const observation=window.prompt('Observation de contrôle/validation :','')??'';const out=await rachatService.transition(String(r.id_rachat),next,observation);setMessage(out.error?.message??`Dossier passé à ${next}.`);if(!out.error)await load()};
 const pay=async(r:Rachat)=>{const ref=window.prompt('Référence bancaire obligatoire :','');if(!ref)return;const out=await rachatService.pay(String(r.id_rachat),{datePaiement:new Date().toISOString().slice(0,10),referencePaiement:ref,modePaiement:'VIREMENT'});setMessage(out.error?.message??'Rachat payé et compte ESR soldé.');if(!out.error)await load()};
 const pdf=async(r:Rachat)=>{const out=await rachatService.pdf(String(r.id_rachat));if(out.error||!out.data){setMessage(out.error?.message??'PDF indisponible');return}const u=URL.createObjectURL(out.data),a=document.createElement('a');a.href=u;a.download=`rachat-${r.id_rachat}.pdf`;a.click();URL.revokeObjectURL(u)};
 return <div className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-extrabold text-slate-800 flex items-center gap-2"><WalletCards className="text-orange-500"/>Rachats & Résiliations</h1><p className="text-xs text-slate-500 mt-1">Rachat total uniquement · contrôle séparé · liquidation traçable</p></div><button onClick={()=>setShow(!show)} className="px-4 py-2 bg-orange-500 text-white rounded-xl text-xs font-bold flex gap-2"><Plus size={16}/>Nouvelle demande</button></div>
  {message&&<div className="p-3 rounded-xl bg-blue-50 border border-blue-100 text-sm text-blue-800">{message}</div>}
  {show&&<form onSubmit={create} className="bg-white border rounded-2xl p-5 grid md:grid-cols-3 gap-4"><select required value={form.adherentId} onChange={e=>setForm({...form,adherentId:e.target.value})} className="border rounded-xl px-3 py-2 text-sm"><option value="">Adhérent actif…</option>{ads.map(a=><option key={a.id_adherent} value={a.id_adherent}>{a.matricule} — {a.nom} {a.prenoms}</option>)}</select><input type="date" required value={form.dateDemande} onChange={e=>setForm({...form,dateDemande:e.target.value})} className="border rounded-xl px-3 py-2 text-sm"/><input placeholder="Motif / référence de demande" value={form.motif} onChange={e=>setForm({...form,motif:e.target.value})} className="border rounded-xl px-3 py-2 text-sm"/><div className="md:col-span-3 text-xs text-amber-700 bg-amber-50 p-3 rounded-xl">Éligibilité automatique : période de cotisation, 2 années complètes, au moins 8 mouvements encaissés, aucune rente active. Formule provisoire : PM moins 5 % de frais, puis 5 % de pénalité.</div><button disabled={busy} className="bg-slate-800 text-white rounded-xl px-4 py-2 text-xs font-bold">Calculer et ouvrir</button></form>}
  <div className="bg-white border rounded-2xl p-4 flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Matricule, nom…" className="w-full border rounded-xl pl-9 pr-3 py-2 text-sm"/></div><select value={statut} onChange={e=>setStatut(e.target.value)} className="border rounded-xl px-3 text-sm"><option>TOUS</option>{['DOSSIER_OUVERT','EN_CONTROLE','VALIDE','PAYE','REJETE','ANNULE'].map(s=><option key={s}>{s}</option>)}</select><button onClick={load} className="p-2 border rounded-xl"><RefreshCw size={17} className={busy?'animate-spin':''}/></button></div>
  <ScrollableTableWrapper><table className="min-w-full bg-white text-xs"><thead className="bg-slate-100 uppercase text-slate-600"><tr>{['Adhérent','Demande','Statut','PM','Frais','Pénalité','Net à payer','Contrôles','Actions'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id_rachat} className="hover:bg-slate-50"><td className="p-3 font-bold">{r.matricule}<br/><span className="font-normal">{r.nom} {r.prenoms}</span></td><td className="p-3">{formatDateFr(r.date_demande)}</td><td className="p-3"><span className="px-2 py-1 rounded-full bg-amber-100 font-bold">{r.statut}</span></td><td className="p-3 text-right">{formatFCFA(r.provision_mathematique)}</td><td className="p-3 text-right">{formatFCFA(r.frais_gestion)}</td><td className="p-3 text-right">{formatFCFA(r.penalite)}</td><td className="p-3 text-right font-extrabold text-emerald-700">{formatFCFA(r.montant_net)}</td><td className="p-3">{r.anciennete_annees} ans · {r.nombre_mouvements} mvts</td><td className="p-3"><div className="flex gap-2">{['DOSSIER_OUVERT','EN_CONTROLE'].includes(r.statut)&&<button onClick={()=>advance(r)} className="px-2 py-1 bg-blue-600 text-white rounded">Avancer</button>}{r.statut==='VALIDE'&&<button onClick={()=>pay(r)} className="px-2 py-1 bg-emerald-600 text-white rounded">Payer</button>}<button onClick={()=>pdf(r)} title="Liquidation PDF" className="p-1.5 bg-slate-800 text-white rounded"><Download size={14}/></button></div></td></tr>)}</tbody></table></ScrollableTableWrapper>
  <p className="text-[11px] text-slate-400">Utilisateur connecté : {currentUser.email || currentUser.matricule}. La séparation créateur / contrôleur / valideur / payeur est appliquée côté serveur.</p>
 </div>;
}
