-- Les paiements spontanes volontaires constituent un credit qui diminue les
-- cotisations trimestrielles suivantes. L'excedent est reporte sans limite de
-- trimestre et les regularisations de precompte sont explicitement exclues.

alter table public.precomptes
  add column if not exists montant_cotisation_brut numeric(15,2),
  add column if not exists montant_credit_spontane numeric(15,2) not null default 0;

update public.precomptes
set montant_cotisation_brut = montant_depart
where montant_cotisation_brut is null;

alter table public.precomptes
  alter column montant_cotisation_brut set not null;

create table if not exists public.imputations_paiements_spontanes (
  id_imputation bigint generated by default as identity primary key,
  id_cotisation_detail_spontanee bigint not null
    references public.cotisation_details(id_cotisation_detail) on delete restrict,
  id_precompte bigint not null
    references public.precomptes(id_precompte) on delete cascade,
  montant_impute numeric(15,2) not null check (montant_impute > 0),
  created_at timestamptz not null default now(),
  unique (id_cotisation_detail_spontanee, id_precompte)
);

create index if not exists idx_imputations_spontanees_detail
  on public.imputations_paiements_spontanes(id_cotisation_detail_spontanee);
create index if not exists idx_imputations_spontanees_precompte
  on public.imputations_paiements_spontanes(id_precompte);

alter table public.imputations_paiements_spontanes enable row level security;
revoke all on public.imputations_paiements_spontanes from public, anon, authenticated;
grant all on public.imputations_paiements_spontanes to service_role;

create or replace function public.imputer_paiements_spontanes_precompte_esr(
  p_id_precompte bigint,
  p_id_adherent bigint,
  p_date_limite date,
  p_montant_brut numeric
) returns table(montant_brut numeric, montant_credit numeric, montant_net numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_restant numeric(15,2) := greatest(coalesce(p_montant_brut, 0), 0);
  v_credit numeric(15,2) := 0;
  v_disponible numeric(15,2);
  v_imputation numeric(15,2);
  v_detail_precompte bigint;
  v_credit_deja_impute numeric(15,2);
  r record;
begin
  if p_montant_brut is null or p_montant_brut < 0 then
    raise exception 'Montant brut de cotisation invalide';
  end if;

  -- Serialise toutes les imputations d'un meme adherent afin d'interdire la
  -- consommation concurrente d'un meme credit sur deux precomptes.
  perform pg_advisory_xact_lock(p_id_adherent);

  select p.id_cotisation_detail
    into v_detail_precompte
  from public.precomptes p
  join public.cotisation_details d
    on d.id_cotisation_detail = p.id_cotisation_detail
  join public.cotisation_entetes e
    on e.id_cotisation_entete = d.id_cotisation_entete
  where p.id_precompte = p_id_precompte
    and e.id_adherent = p_id_adherent
  for update;

  if v_detail_precompte is null then
    raise exception 'Precompte introuvable ou sans detail de cotisation';
  end if;

  select coalesce(sum(i.montant_impute), 0)
    into v_credit_deja_impute
  from public.imputations_paiements_spontanes i
  where i.id_precompte = p_id_precompte;

  if v_credit_deja_impute > 0 then
    select p.montant_cotisation_brut, p.montant_credit_spontane, p.montant_depart
      into montant_brut, montant_credit, montant_net
    from public.precomptes p
    where p.id_precompte = p_id_precompte;
    return next;
    return;
  end if;

  for r in
    select d.id_cotisation_detail, d.montant,
           coalesce((
             select sum(i.montant_impute)
             from public.imputations_paiements_spontanes i
             where i.id_cotisation_detail_spontanee = d.id_cotisation_detail
           ), 0) as deja_impute
    from public.cotisation_details d
    join public.cotisation_entetes e
      on e.id_cotisation_entete = d.id_cotisation_entete
    where e.id_adherent = p_id_adherent
      and upper(coalesce(d.source, '')) in ('SPONTANEE', 'DIRECT')
      and upper(coalesce(d.statut, '')) = 'ENCAISSEE'
      and d.date_valeur is not null
      and d.date_valeur <= p_date_limite
      and d.id_precompte is null
      and d.montant - coalesce((
        select sum(i.montant_impute)
        from public.imputations_paiements_spontanes i
        where i.id_cotisation_detail_spontanee = d.id_cotisation_detail
      ), 0) > 0
    order by d.date_valeur, d.id_cotisation_detail
    for update of d
  loop
    exit when v_restant <= 0;
    v_disponible := greatest(r.montant - r.deja_impute, 0);
    v_imputation := least(v_disponible, v_restant);
    if v_imputation > 0 then
      insert into public.imputations_paiements_spontanes(
        id_cotisation_detail_spontanee, id_precompte, montant_impute
      ) values (r.id_cotisation_detail, p_id_precompte, v_imputation);
      v_credit := v_credit + v_imputation;
      v_restant := v_restant - v_imputation;
    end if;
  end loop;

  update public.precomptes
  set montant_cotisation_brut = p_montant_brut,
      montant_credit_spontane = v_credit,
      montant_depart = greatest(p_montant_brut - v_credit, 0),
      statut_precompte = case
        when greatest(p_montant_brut - v_credit, 0) = 0 then 'ENCAISSE'
        else statut_precompte
      end,
      date_retour = case
        when greatest(p_montant_brut - v_credit, 0) = 0 then p_date_limite
        else date_retour
      end,
      updated_at = now()
  where id_precompte = p_id_precompte;

  update public.cotisation_details
  set montant = greatest(p_montant_brut - v_credit, 0),
      statut = case
        when greatest(p_montant_brut - v_credit, 0) = 0 then 'ENCAISSEE'
        else statut
      end,
      date_valeur = case
        when greatest(p_montant_brut - v_credit, 0) = 0 then p_date_limite
        else date_valeur
      end
  where id_cotisation_detail = v_detail_precompte;

  montant_brut := p_montant_brut;
  montant_credit := v_credit;
  montant_net := greatest(p_montant_brut - v_credit, 0);
  return next;
end;
$$;

revoke all on function public.imputer_paiements_spontanes_precompte_esr(bigint,bigint,date,numeric)
  from public, anon, authenticated;
grant execute on function public.imputer_paiements_spontanes_precompte_esr(bigint,bigint,date,numeric)
  to service_role;
