-- Module autonome de rachat total / résiliation ESR.
create table if not exists public.rachats (
  id_rachat bigint generated by default as identity primary key,
  id_adherent bigint not null references public.adherents(id_adherent),
  date_demande date not null,
  date_arrete date not null,
  motif text,
  statut varchar(30) not null default 'DOSSIER_OUVERT'
    check (statut in ('DOSSIER_OUVERT','EN_CONTROLE','VALIDE','PAYE','REJETE','ANNULE')),
  capital_verse numeric(18,2) not null default 0,
  provision_mathematique numeric(18,2) not null default 0,
  taux_frais_gestion numeric(8,4) not null default 0,
  frais_gestion numeric(18,2) not null default 0,
  taux_penalite numeric(8,4) not null default 0,
  penalite numeric(18,2) not null default 0,
  montant_net numeric(18,2) not null default 0,
  nombre_mouvements integer not null default 0,
  anciennete_annees integer not null default 0,
  version_calcul varchar(100) not null,
  parametres_json jsonb not null default '{}'::jsonb,
  mouvements_json jsonb not null default '[]'::jsonb,
  cree_par varchar(100) not null,
  controle_par varchar(100),
  valide_par varchar(100),
  paye_par varchar(100),
  date_controle timestamptz,
  date_validation timestamptz,
  date_paiement date,
  reference_paiement varchar(120),
  mode_paiement varchar(30),
  observation text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (montant_net >= 0 and provision_mathematique >= 0)
);

create unique index if not exists ux_rachats_dossier_actif
  on public.rachats(id_adherent)
  where statut not in ('PAYE','REJETE','ANNULE');
create index if not exists ix_rachats_date_statut on public.rachats(date_demande desc, statut);

create table if not exists public.rachat_evenements (
  id_evenement bigint generated by default as identity primary key,
  id_rachat bigint not null references public.rachats(id_rachat) on delete restrict,
  ancien_statut varchar(30),
  nouveau_statut varchar(30) not null,
  utilisateur varchar(100) not null,
  observation text,
  created_at timestamptz not null default now()
);

create or replace view public.v_rachats_details as
select r.*, a.matricule, a.nom, a.prenoms, a.date_souscription
from public.rachats r
join public.adherents a on a.id_adherent = r.id_adherent;

create or replace function public.payer_rachat_esr(
  p_id_rachat bigint, p_utilisateur varchar, p_date_paiement date,
  p_reference varchar, p_mode varchar, p_observation text default null
) returns public.rachats language plpgsql security definer set search_path = public as $$
declare v public.rachats; v_matricule text; v_annee integer; v_trimestre integer;
begin
  select * into v from public.rachats where id_rachat=p_id_rachat for update;
  if not found then raise exception 'Rachat introuvable'; end if;
  if v.statut <> 'VALIDE' then raise exception 'Le rachat doit être validé avant paiement'; end if;
  if coalesce(trim(p_reference),'') = '' then raise exception 'Référence de paiement obligatoire'; end if;
  update public.rachats set statut='PAYE', paye_par=p_utilisateur,
    date_paiement=p_date_paiement, reference_paiement=p_reference,
    mode_paiement=p_mode, observation=coalesce(p_observation,observation), updated_at=now()
  where id_rachat=p_id_rachat returning * into v;
  update public.comptes_esr set capital_acquis=0, pp=0, pu=0, pm=0, valeur_rachat=0,
    date_calcul=p_date_paiement, version_calc='ESR-RACHAT-SOLDE', updated_at=now()
  where id_adherent=v.id_adherent;
  update public.adherents set statut=false, etat='RESILIE', updated_at=now()
  where id_adherent=v.id_adherent;
  select matricule into v_matricule from public.adherents where id_adherent=v.id_adherent;
  v_annee := extract(year from p_date_paiement)::integer;
  v_trimestre := extract(quarter from p_date_paiement)::integer;
  update public.precomptes set statut_precompte='ANNULE', updated_at=now()
  where matricule=v_matricule
    and (annee>v_annee or (annee=v_annee and trimestre>=v_trimestre))
    and statut_precompte in ('GENERE','INITIE','NON_PRECOMPTE');
  insert into public.rachat_evenements(id_rachat,ancien_statut,nouveau_statut,utilisateur,observation)
  values(p_id_rachat,'VALIDE','PAYE',p_utilisateur,p_observation);
  return v;
end $$;
