-- Cloture ESR auditable et atomique.
-- Compatibilite avec les bases encore equipees de l'ancien referentiel.
do $$
begin
  if to_regclass('public.periodes') is null
     and to_regclass('public.periodes_precompte') is not null then
    alter table public.periodes_precompte rename to periodes;
  end if;
end $$;

create table if not exists public.periodes (
  periode text primary key,
  annee integer not null,
  trimestre integer not null check (trimestre between 1 and 4),
  statut text not null default 'OUVERTE' check (statut in ('OUVERTE', 'CLOTUREE')),
  date_cloture timestamptz,
  cloture_par uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_periodes_statut on public.periodes (statut);

alter table public.periodes add column if not exists date_ouverture date;
alter table public.periodes add column if not exists date_cloture_prevue date;
alter table public.periodes add column if not exists date_cloture_effective date;

update public.periodes
set date_ouverture = make_date(annee, ((trimestre - 1) * 3) + 1, 1),
    date_cloture_prevue = (make_date(annee, (trimestre * 3), 1) + interval '1 month - 1 day')::date
where date_ouverture is null or date_cloture_prevue is null;

create table if not exists public.historique_actuariel_esr (
  id_historique bigint generated by default as identity primary key,
  id_adherent bigint not null,
  periode text not null references public.periodes(periode),
  capital_acquis numeric(18,2) not null default 0,
  provision_mathematique numeric(18,2) not null default 0,
  taux_technique numeric(12,8) not null default 0,
  date_valeur date not null,
  date_cloture date not null,
  version_calc text not null,
  created_at timestamptz not null default now(),
  unique (id_adherent, periode)
);

create table if not exists public.historique_cotisations_esr (
  id_historique bigint generated by default as identity primary key,
  id_adherent bigint not null,
  periode text not null references public.periodes(periode),
  montant_cotise numeric(18,2) not null default 0,
  interets_credites numeric(18,2) not null default 0,
  capital_cumule numeric(18,2) not null default 0,
  pm numeric(18,2) not null default 0,
  valeur_rachat numeric(18,2) not null default 0,
  date_valeur date not null,
  version_calc text not null,
  cree_par uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (id_adherent, periode)
);

create table if not exists public.resumes_cloture_esr (
  id_resume bigint generated by default as identity primary key,
  periode text not null unique references public.periodes(periode),
  nb_adherents integer not null,
  capital_global numeric(18,2) not null default 0,
  pm_totale numeric(18,2) not null default 0,
  date_cloture date not null,
  version_calc text not null,
  cloture_par uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create or replace function public.cloturer_periode_esr(
  p_periode text,
  p_user_id uuid,
  p_snapshots jsonb,
  p_resume jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_periode public.periodes%rowtype;
  v_annee integer;
  v_trimestre integer;
  v_periode_suivante text;
  v_date_ouverture date;
  v_date_cloture_prevue date;
begin
  select * into v_periode from public.periodes where periode = upper(p_periode) for update;
  if not found then raise exception 'PERIODE_INTROUVABLE'; end if;
  if v_periode.statut <> 'OUVERTE' then raise exception 'PERIODE_DEJA_CLOTUREE'; end if;

  insert into public.historique_actuariel_esr
    (id_adherent, periode, capital_acquis, provision_mathematique, taux_technique, date_valeur, date_cloture, version_calc)
  select id_adherent, v_periode.periode, capital_acquis, provision_mathematique, taux_technique,
         date_valeur, current_date, version_calc
  from jsonb_to_recordset(coalesce(p_snapshots, '[]'::jsonb)) as x(
    id_adherent bigint, capital_acquis numeric, provision_mathematique numeric,
    montant_cotise numeric, interets_credites numeric, valeur_rachat numeric,
    taux_technique numeric, date_valeur date, version_calc text
  );

  insert into public.historique_cotisations_esr
    (id_adherent, periode, montant_cotise, interets_credites, capital_cumule, pm, valeur_rachat, date_valeur, version_calc, cree_par)
  select id_adherent, v_periode.periode, montant_cotise, interets_credites, capital_acquis,
         provision_mathematique, valeur_rachat, date_valeur, version_calc, p_user_id
  from jsonb_to_recordset(coalesce(p_snapshots, '[]'::jsonb)) as x(
    id_adherent bigint, capital_acquis numeric, provision_mathematique numeric,
    montant_cotise numeric, interets_credites numeric, valeur_rachat numeric,
    taux_technique numeric, date_valeur date, version_calc text
  );

  update public.comptes_esr c
  set capital_acquis = x.capital_acquis,
      pm = x.provision_mathematique,
      valeur_rachat = x.valeur_rachat,
      date_calcul = x.date_valeur,
      version_calc = x.version_calc,
      updated_at = now()
  from jsonb_to_recordset(coalesce(p_snapshots, '[]'::jsonb)) as x(
    id_adherent bigint, capital_acquis numeric, provision_mathematique numeric,
    montant_cotise numeric, interets_credites numeric, valeur_rachat numeric,
    taux_technique numeric, date_valeur date, version_calc text
  ) where c.id_adherent = x.id_adherent;

  insert into public.comptes_esr (id_adherent, capital_acquis, pm, valeur_rachat, date_calcul, version_calc)
  select x.id_adherent, x.capital_acquis, x.provision_mathematique, x.valeur_rachat, x.date_valeur, x.version_calc
  from jsonb_to_recordset(coalesce(p_snapshots, '[]'::jsonb)) as x(
    id_adherent bigint, capital_acquis numeric, provision_mathematique numeric,
    montant_cotise numeric, interets_credites numeric, valeur_rachat numeric,
    taux_technique numeric, date_valeur date, version_calc text
  ) where not exists (select 1 from public.comptes_esr c where c.id_adherent = x.id_adherent);

  insert into public.resumes_cloture_esr
    (periode, nb_adherents, capital_global, pm_totale, date_cloture, version_calc, cloture_par)
  values (
    v_periode.periode,
    coalesce((p_resume->>'nb_adherents')::integer, 0),
    coalesce((p_resume->>'capital_global')::numeric, 0),
    coalesce((p_resume->>'pm_totale')::numeric, 0),
    current_date,
    coalesce(p_resume->>'version_calc', 'ESR-PM-1'),
    p_user_id
  );

  update public.periodes
  set statut = 'CLOTUREE', date_cloture = now(), date_cloture_effective = current_date,
      cloture_par = p_user_id, updated_at = now()
  where periode = v_periode.periode;

  if v_periode.trimestre < 4 then
    v_annee := v_periode.annee; v_trimestre := v_periode.trimestre + 1;
  else
    v_annee := v_periode.annee + 1; v_trimestre := 1;
  end if;
  v_periode_suivante := v_annee::text || 'T' || v_trimestre::text;
  v_date_ouverture := make_date(v_annee, ((v_trimestre - 1) * 3) + 1, 1);
  v_date_cloture_prevue := (make_date(v_annee, v_trimestre * 3, 1) + interval '1 month - 1 day')::date;

  insert into public.periodes
    (periode, annee, trimestre, statut, date_ouverture, date_cloture_prevue)
  values (v_periode_suivante, v_annee, v_trimestre, 'OUVERTE', v_date_ouverture, v_date_cloture_prevue)
  on conflict (periode) do update set statut = 'OUVERTE', updated_at = now();

  return jsonb_build_object('periode_suivante', v_periode_suivante);
end;
$$;

revoke all on function public.cloturer_periode_esr(text, uuid, jsonb, jsonb) from public;
grant execute on function public.cloturer_periode_esr(text, uuid, jsonb, jsonb) to service_role;
